version: '3'

services:
  database:
    extends:
      file: common-services.yml
      service: database
    volumes:
      - ./apps/database:/app/apps/database
  # api:
  #   extends:
  #     file: common-services.yml
  #     service: api
  #   volumes:
  #     - ./apps/api:/app/apps/api
  #     - ./apps/api/node_modules:/app/apps/api/node_modules
  #     - /app/node_modules
  #     - /app/
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile.dev
  #   environment:
  #     - NODE_ENV=development
  # next:
  #   extends:
  #     file: common-services.yml
  #     service: next
  #   build:
  #     context: .
  #     dockerfile: ./apps/next/Dockerfile.dev
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./:/app
  #     - ./apps/next/node_modules:/app/apps/next/node_modules
  #     - /app/node_modules
  #     - /app/.next
  # reverse-proxy:
  #   extends:
  #     file: common-services.yml
  #     service: reverse-proxy

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  starter_app_network:
    external: true
