version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - starter_app_network
    expose:
      - '8080'
    env_file:
      - .env
  next:
    container_name: next
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - starter_app_network
    env_file:
      - .env
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - 3050:80
    depends_on:
      - next
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
