version: '3'

services:
  next:
    extends:
      file: common-services.yml
      service: next
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile.dev
    environment:
      - VERBECC_API=http://localhost:8000
      - NODE_ENV=development
      - NEXT_PUBLIC_TRPC_API=http://localhost:8080
    volumes:
      - ./:/app
      - ./apps/next/node_modules:/app/apps/next/node_modules
      - /app/node_modules
      - /app/.next
  reverse-proxy:
    extends:
      file: common-services.yml
      service: reverse-proxy

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  starter_app_network:
    external: true
