FROM node:18-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN apt-get update -qq && apt-get install -y openssl
# This Dockerfile is copy-pasted into our main docs at /docs/handbook/deploying-with-docker.
# Make sure you update both files!

FROM base AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
# Set working directory
WORKDIR /app
RUN yarn global add turbo
COPY . .
#RUN pnpm global add turbo
RUN turbo prune --scope=next-app --docker

# Add lockfile and package.json's of  isolated subworkspace
FROM base AS installer
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN apt-get update
RUN apt-get update -qq && \
    apt-get install -y openssl
WORKDIR /app
RUN yarn global add pnpm
ENTRYPOINT ["sh", "./entrypoint.sh"]

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY tsconfig.json tsconfig.json
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY packages/app /app/packages/app
COPY packages/ui /app/packages/ui
COPY packages/schema /app/packages/schema
COPY packages/tsconfig /app/packages/tsconfig
COPY apps/api /app/apps/api
COPY packages/eslint-config-custom /app/packages/eslint-config-custom

# COPY packages/database /app/packages/database
# COPY apps/api /app/apps/api
COPY apps/next /app/apps/next
RUN pnpm install

# Build the project
# COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

# Uncomment and use build args to enable remote caching
# ARG TURBO_TEAM
# ENV TURBO_TEAM=$TURBO_TEAM

# ARG TURBO_TOKEN
# ENV TURBO_TOKEN=$TURBO_TOKEN

RUN pnpm turbo run build --filter=next-app...
# CMD ["tail", "-f", "/dev/null"]

FROM base as runner
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@7.4.1 --activate
COPY --from=installer /app/ .
WORKDIR /app/apps/next/
CMD [ "pnpm", "dev" ]